version: '2'
services:
  web:
    build: .
    command: /go/bin/gin run main.go
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    depends_on:
      - redis
    ports:
      - "3030:3000"
    environment:
      PORT: 3030
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
  redis:
    image: redis:3.2.10-alpine
