version: '2'
services:
  xslt-api:
    container_name: xslt-api
    build: .
    command: /go/bin/gin run main.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    depends_on:
      - redis
    ports:
      - "3030:3000"
    environment:
      PORT: 3030
      GET_FETCH_XML_URL: http://google.com
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    external_links:
      - redis
      - query-api
    network_mode: bridge
    # networks:
    #   - fmi
  redis:
    container_name: redis
    image: redis:3.2.10-alpine
    network_mode: bridge
    # networks:
    #   - fmi
    # external_links:
    #   - xslt-api
# networks:
#   fmi:
#     driver: bridge
